apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: admission-controller
build:
  platforms:
    - linux/amd64
    - linux/arm64
  artifacts:
    - image: jumads/admission-controller
      context: k8s-admission-controller
      docker:
        noCache: false
        dockerfile: Dockerfile
        cacheFrom:
          - jumads/admission-controller
  local:
    push: true
    tryImportMissing: true
    useDockerCLI: false
    useBuildkit: true
  tagPolicy:
    gitCommit:
      prefix: local-
      variant: CommitSha
      ignoreChanges: true
deploy:
  kubeContext: docker-desktop
manifests:
  kustomize:
    paths:
      - manifests/webhooks
      - manifests/tests