apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: admission-controller
build:
  artifacts:
    - image: jumads/admission-controller
      context: .
      docker:
        noCache: true # Disable cache for the build to ensure the latest script code is used for the entrypoint
        dockerfile: Dockerfile
  local:
    push: true
    useDockerCLI: false
    useBuildkit: true
  tagPolicy:
    gitCommit:
      prefix: local
deploy:
  kubeContext: docker-desktop
  kubectl:
    manifests:
      - manifests/*
    # flags:
    #   apply:
    #     - --prune
    #     - --all=true