apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admission-webhook-cert
  namespace: default
spec:
  secretName: webhook-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  subject:
    organizations:
      - Juma
  commonName: pod-admission-controller.default.svc  
  dnsNames:
    - pod-admission-controller
    - pod-admission-controller.default
    - pod-admission-controller.default.svc
    - pod-admission-controller.default.svc.cluster.local
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer