apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pod-status-validator
  annotations:
    cert-manager.io/inject-ca-from: default/admission-webhook-cert
webhooks:
  - name: pod-status-validator.default.svc.cluster.local
    matchPolicy: Equivalent
    timeoutSeconds: 5
    failurePolicy: Fail
    sideEffects: None
    clientConfig:
      service:
        namespace: default
        name: pod-admission-controller
        path: /validate-pod-status
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["UPDATE"]
        resources: ["pods/status"]
        scope: "*"
    admissionReviewVersions:
      - "v1"
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: ["kube-system", "cert-manager", "pod-labels-operator-system"]
    objectSelector:
      matchExpressions:
        - key: missingLabelsValues
          operator: In
          values: ["true"]
        - key: app
          operator: NotIn
          values: ["pod-admission-controller"] 